kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # TODO: use upstream image when released, see: https://hub.docker.com/r/kindest/node/tags
    # Build custom image with: kind build node-image --type release --image kindest/node:1.36.1 1.36.1
    image: &image mmontes11/kind:1.36.1
  - role: worker
    image: *image
  - role: worker
    image: *image
  - role: worker
    image: *image
  - role: worker
    image: *image