/*
The MIT License (MIT)

Copyright © 2023 MariaDB Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BackupListerExpansion allows custom methods to be added to
// BackupLister.
type BackupListerExpansion interface{}

// BackupNamespaceListerExpansion allows custom methods to be added to
// BackupNamespaceLister.
type BackupNamespaceListerExpansion interface{}

// ConnectionListerExpansion allows custom methods to be added to
// ConnectionLister.
type ConnectionListerExpansion interface{}

// ConnectionNamespaceListerExpansion allows custom methods to be added to
// ConnectionNamespaceLister.
type ConnectionNamespaceListerExpansion interface{}

// DatabaseListerExpansion allows custom methods to be added to
// DatabaseLister.
type DatabaseListerExpansion interface{}

// DatabaseNamespaceListerExpansion allows custom methods to be added to
// DatabaseNamespaceLister.
type DatabaseNamespaceListerExpansion interface{}

// GrantListerExpansion allows custom methods to be added to
// GrantLister.
type GrantListerExpansion interface{}

// GrantNamespaceListerExpansion allows custom methods to be added to
// GrantNamespaceLister.
type GrantNamespaceListerExpansion interface{}

// MariaDBListerExpansion allows custom methods to be added to
// MariaDBLister.
type MariaDBListerExpansion interface{}

// MariaDBNamespaceListerExpansion allows custom methods to be added to
// MariaDBNamespaceLister.
type MariaDBNamespaceListerExpansion interface{}

// MaxScaleListerExpansion allows custom methods to be added to
// MaxScaleLister.
type MaxScaleListerExpansion interface{}

// MaxScaleNamespaceListerExpansion allows custom methods to be added to
// MaxScaleNamespaceLister.
type MaxScaleNamespaceListerExpansion interface{}

// RestoreListerExpansion allows custom methods to be added to
// RestoreLister.
type RestoreListerExpansion interface{}

// RestoreNamespaceListerExpansion allows custom methods to be added to
// RestoreNamespaceLister.
type RestoreNamespaceListerExpansion interface{}

// SqlJobListerExpansion allows custom methods to be added to
// SqlJobLister.
type SqlJobListerExpansion interface{}

// SqlJobNamespaceListerExpansion allows custom methods to be added to
// SqlJobNamespaceLister.
type SqlJobNamespaceListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// UserNamespaceListerExpansion allows custom methods to be added to
// UserNamespaceLister.
type UserNamespaceListerExpansion interface{}
