/*
The MIT License (MIT)

Copyright © 2023 MariaDB Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	mariadbv1alpha1 "github.com/mariadb-operator/mariadb-operator/api/mariadb/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GrantLister helps list Grants.
// All objects returned here must be treated as read-only.
type GrantLister interface {
	// List lists all Grants in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mariadbv1alpha1.Grant, err error)
	// Grants returns an object that can list and get Grants.
	Grants(namespace string) GrantNamespaceLister
	GrantListerExpansion
}

// grantLister implements the GrantLister interface.
type grantLister struct {
	listers.ResourceIndexer[*mariadbv1alpha1.Grant]
}

// NewGrantLister returns a new GrantLister.
func NewGrantLister(indexer cache.Indexer) GrantLister {
	return &grantLister{listers.New[*mariadbv1alpha1.Grant](indexer, mariadbv1alpha1.Resource("grant"))}
}

// Grants returns an object that can list and get Grants.
func (s *grantLister) Grants(namespace string) GrantNamespaceLister {
	return grantNamespaceLister{listers.NewNamespaced[*mariadbv1alpha1.Grant](s.ResourceIndexer, namespace)}
}

// GrantNamespaceLister helps list and get Grants.
// All objects returned here must be treated as read-only.
type GrantNamespaceLister interface {
	// List lists all Grants in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mariadbv1alpha1.Grant, err error)
	// Get retrieves the Grant from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*mariadbv1alpha1.Grant, error)
	GrantNamespaceListerExpansion
}

// grantNamespaceLister implements the GrantNamespaceLister
// interface.
type grantNamespaceLister struct {
	listers.ResourceIndexer[*mariadbv1alpha1.Grant]
}
