/*
The MIT License (MIT)

Copyright © 2023 MariaDB Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	mariadbv1alpha1 "github.com/mariadb-operator/mariadb-operator/api/mariadb/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MariaDBLister helps list MariaDBs.
// All objects returned here must be treated as read-only.
type MariaDBLister interface {
	// List lists all MariaDBs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mariadbv1alpha1.MariaDB, err error)
	// MariaDBs returns an object that can list and get MariaDBs.
	MariaDBs(namespace string) MariaDBNamespaceLister
	MariaDBListerExpansion
}

// mariaDBLister implements the MariaDBLister interface.
type mariaDBLister struct {
	listers.ResourceIndexer[*mariadbv1alpha1.MariaDB]
}

// NewMariaDBLister returns a new MariaDBLister.
func NewMariaDBLister(indexer cache.Indexer) MariaDBLister {
	return &mariaDBLister{listers.New[*mariadbv1alpha1.MariaDB](indexer, mariadbv1alpha1.Resource("mariadb"))}
}

// MariaDBs returns an object that can list and get MariaDBs.
func (s *mariaDBLister) MariaDBs(namespace string) MariaDBNamespaceLister {
	return mariaDBNamespaceLister{listers.NewNamespaced[*mariadbv1alpha1.MariaDB](s.ResourceIndexer, namespace)}
}

// MariaDBNamespaceLister helps list and get MariaDBs.
// All objects returned here must be treated as read-only.
type MariaDBNamespaceLister interface {
	// List lists all MariaDBs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mariadbv1alpha1.MariaDB, err error)
	// Get retrieves the MariaDB from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*mariadbv1alpha1.MariaDB, error)
	MariaDBNamespaceListerExpansion
}

// mariaDBNamespaceLister implements the MariaDBNamespaceLister
// interface.
type mariaDBNamespaceLister struct {
	listers.ResourceIndexer[*mariadbv1alpha1.MariaDB]
}
