/*
The MIT License (MIT)

Copyright © 2023 MariaDB Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	mariadbv1alpha1 "github.com/mariadb-operator/mariadb-operator/api/mariadb/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RestoreLister helps list Restores.
// All objects returned here must be treated as read-only.
type RestoreLister interface {
	// List lists all Restores in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mariadbv1alpha1.Restore, err error)
	// Restores returns an object that can list and get Restores.
	Restores(namespace string) RestoreNamespaceLister
	RestoreListerExpansion
}

// restoreLister implements the RestoreLister interface.
type restoreLister struct {
	listers.ResourceIndexer[*mariadbv1alpha1.Restore]
}

// NewRestoreLister returns a new RestoreLister.
func NewRestoreLister(indexer cache.Indexer) RestoreLister {
	return &restoreLister{listers.New[*mariadbv1alpha1.Restore](indexer, mariadbv1alpha1.Resource("restore"))}
}

// Restores returns an object that can list and get Restores.
func (s *restoreLister) Restores(namespace string) RestoreNamespaceLister {
	return restoreNamespaceLister{listers.NewNamespaced[*mariadbv1alpha1.Restore](s.ResourceIndexer, namespace)}
}

// RestoreNamespaceLister helps list and get Restores.
// All objects returned here must be treated as read-only.
type RestoreNamespaceLister interface {
	// List lists all Restores in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*mariadbv1alpha1.Restore, err error)
	// Get retrieves the Restore from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*mariadbv1alpha1.Restore, error)
	RestoreNamespaceListerExpansion
}

// restoreNamespaceLister implements the RestoreNamespaceLister
// interface.
type restoreNamespaceLister struct {
	listers.ResourceIndexer[*mariadbv1alpha1.Restore]
}
