apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - sql/database.yaml
  - sql/grant.yaml
  - sql/user.yaml
  - sysbench-prepare-galera_job.yaml
  - sysbench-galera_cronjob.yaml