/*
The MIT License (MIT)

Copyright © 2023 MariaDB Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	mariadbv1alpha1 "github.com/mariadb-operator/mariadb-operator/api/mariadb/v1alpha1"
	scheme "github.com/mariadb-operator/mariadb-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DatabasesGetter has a method to return a DatabaseInterface.
// A group's client should implement this interface.
type DatabasesGetter interface {
	Databases(namespace string) DatabaseInterface
}

// DatabaseInterface has methods to work with Database resources.
type DatabaseInterface interface {
	Create(ctx context.Context, database *mariadbv1alpha1.Database, opts v1.CreateOptions) (*mariadbv1alpha1.Database, error)
	Update(ctx context.Context, database *mariadbv1alpha1.Database, opts v1.UpdateOptions) (*mariadbv1alpha1.Database, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, database *mariadbv1alpha1.Database, opts v1.UpdateOptions) (*mariadbv1alpha1.Database, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*mariadbv1alpha1.Database, error)
	List(ctx context.Context, opts v1.ListOptions) (*mariadbv1alpha1.DatabaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *mariadbv1alpha1.Database, err error)
	DatabaseExpansion
}

// databases implements DatabaseInterface
type databases struct {
	*gentype.ClientWithList[*mariadbv1alpha1.Database, *mariadbv1alpha1.DatabaseList]
}

// newDatabases returns a Databases
func newDatabases(c *MariadbV1alpha1Client, namespace string) *databases {
	return &databases{
		gentype.NewClientWithList[*mariadbv1alpha1.Database, *mariadbv1alpha1.DatabaseList](
			"databases",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *mariadbv1alpha1.Database { return &mariadbv1alpha1.Database{} },
			func() *mariadbv1alpha1.DatabaseList { return &mariadbv1alpha1.DatabaseList{} },
		),
	}
}
