/*
The MIT License (MIT)

Copyright © 2023 MariaDB Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	mariadbv1alpha1 "github.com/mariadb-operator/mariadb-operator/api/mariadb/v1alpha1"
	scheme "github.com/mariadb-operator/mariadb-operator/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type MariadbV1alpha1Interface interface {
	RESTClient() rest.Interface
	BackupsGetter
	ConnectionsGetter
	DatabasesGetter
	GrantsGetter
	MariaDBsGetter
	MaxScalesGetter
	RestoresGetter
	SqlJobsGetter
	UsersGetter
}

// MariadbV1alpha1Client is used to interact with features provided by the mariadb group.
type MariadbV1alpha1Client struct {
	restClient rest.Interface
}

func (c *MariadbV1alpha1Client) Backups(namespace string) BackupInterface {
	return newBackups(c, namespace)
}

func (c *MariadbV1alpha1Client) Connections(namespace string) ConnectionInterface {
	return newConnections(c, namespace)
}

func (c *MariadbV1alpha1Client) Databases(namespace string) DatabaseInterface {
	return newDatabases(c, namespace)
}

func (c *MariadbV1alpha1Client) Grants(namespace string) GrantInterface {
	return newGrants(c, namespace)
}

func (c *MariadbV1alpha1Client) MariaDBs(namespace string) MariaDBInterface {
	return newMariaDBs(c, namespace)
}

func (c *MariadbV1alpha1Client) MaxScales(namespace string) MaxScaleInterface {
	return newMaxScales(c, namespace)
}

func (c *MariadbV1alpha1Client) Restores(namespace string) RestoreInterface {
	return newRestores(c, namespace)
}

func (c *MariadbV1alpha1Client) SqlJobs(namespace string) SqlJobInterface {
	return newSqlJobs(c, namespace)
}

func (c *MariadbV1alpha1Client) Users(namespace string) UserInterface {
	return newUsers(c, namespace)
}

// NewForConfig creates a new MariadbV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*MariadbV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new MariadbV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*MariadbV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &MariadbV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new MariadbV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MariadbV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MariadbV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *MariadbV1alpha1Client {
	return &MariadbV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := mariadbv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MariadbV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
