apiVersion: k8s.mariadb.com/v1alpha1
kind: PhysicalBackup
metadata:
  name: physicalbackup
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "0 2 * * *"      # daily at 02:00
    # onDemand: "1"        # update this identifier to schedule an on-demand backup.
  target: Replica          # zero impact on the primary
  compression: bzip2
  maxRetention: 720h       # 30 days
  storage:
    # S3-compatible (AWS S3, MinIO, GCS, …)
    s3:
      bucket: physicalbackups
      prefix: mariadb
      endpoint: s3.amazonaws.com
      region: us-east-1
      accessKeyIdSecretKeyRef:
        name: s3-credentials
        key: access-key-id
      secretAccessKeySecretKeyRef:
        name: s3-credentials
        key: secret-access-key
    # azureBlob: { … }      # Azure Blob Storage
    # volumeSnapshot: { … } # consistent, near-instant
