package replication

import "path/filepath"

var (
	// BinlogFileName is the file generated by mariadb-backup that contains the binlog position.
	BinlogFileName = "mariadb_backup_binlog_info"
	// LegacyBinlogFileName is the file generated by mariadb-backup < 11.4 that contains the binlog position.
	// This file has been renamed in MariaDB 11.4. We should be compatible with both.
	LegacyBinlogFileName = "xtrabackup_binlog_info"
	// MariaDBOperatorFileName is file that contains the GTID position from the binary log.
	// This file is created by the operator for restoration purposes.
	MariaDBOperatorFileName = "mariadb-operator.info"
	// MariaDBOperatorFilePath is the full path of the mariadb-operator file.
	MariaDBOperatorFilePath = filepath.Join("/var/lib/mysql", MariaDBOperatorFileName)
	// MasterInfoFileName is a file where the replicas keep the connection details to the master.
	MasterInfoFileName = "master.info"
	// RelayLogFileName is the log file where the replicas keep a record of the transactions synced from the primary.
	// See: https://mariadb.com/docs/server/server-management/server-monitoring-logs/binary-log/relay-log.
	RelayLogFileName = "relay-log.info"
)
