package replication

import "path/filepath"

var (
	// BinlogFileName is the file generated by mariadb-backup that contains the binlog position.
	BinlogFileName = "mariadb_backup_binlog_info"
	// LegacyBinlogFileName is the file generated by mariadb-backup < 11.4 that contains the binlog position.
	// This file has been renamed in MariaDB 11.4. We should be compatible with both.
	LegacyBinlogFileName = "xtrabackup_binlog_info"
	// MariaDBBackupDir is a subdirectory of the data directory that contains the binlog position file.
	MariaDBBackupDir = ".mariadb-backup"
	// MariaDBBackupDirPath is the full path of the mariadb-backup directory
	MariaDBBackupDirPath = filepath.Join("/var/lib/mysql", MariaDBBackupDir)
)
