apiVersion: v1
kind: Service
metadata:
  name: mdb-pitr-0-lb
  namespace: default
  annotations:
    metallb.io/loadBalancerIPs: $CIDR_PREFIX.0.55
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: agent
    port: 5555
    protocol: TCP
    targetPort: 5555
  - name: agent-probe
    port: 5566
    protocol: TCP
    targetPort: 5566
  selector:
    app.kubernetes.io/instance: mdb-pitr
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: mdb-pitr-0
  publishNotReadyAddresses: true
  type: LoadBalancer
