/*
The MIT License (MIT)

Copyright © 2023 MariaDB Corporation

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mariadb-operator/mariadb-operator/pkg/client/clientset/versioned/typed/mariadb/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMariadbV1alpha1 struct {
	*testing.Fake
}

func (c *FakeMariadbV1alpha1) Backups(namespace string) v1alpha1.BackupInterface {
	return newFakeBackups(c, namespace)
}

func (c *FakeMariadbV1alpha1) Connections(namespace string) v1alpha1.ConnectionInterface {
	return newFakeConnections(c, namespace)
}

func (c *FakeMariadbV1alpha1) Databases(namespace string) v1alpha1.DatabaseInterface {
	return newFakeDatabases(c, namespace)
}

func (c *FakeMariadbV1alpha1) Grants(namespace string) v1alpha1.GrantInterface {
	return newFakeGrants(c, namespace)
}

func (c *FakeMariadbV1alpha1) MariaDBs(namespace string) v1alpha1.MariaDBInterface {
	return newFakeMariaDBs(c, namespace)
}

func (c *FakeMariadbV1alpha1) MaxScales(namespace string) v1alpha1.MaxScaleInterface {
	return newFakeMaxScales(c, namespace)
}

func (c *FakeMariadbV1alpha1) Restores(namespace string) v1alpha1.RestoreInterface {
	return newFakeRestores(c, namespace)
}

func (c *FakeMariadbV1alpha1) SqlJobs(namespace string) v1alpha1.SqlJobInterface {
	return newFakeSqlJobs(c, namespace)
}

func (c *FakeMariadbV1alpha1) Users(namespace string) v1alpha1.UserInterface {
	return newFakeUsers(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMariadbV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
