{{- include "mariadb-cluster.validateMariaDB" . -}}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "mariadb-cluster.fullname" . }}
  labels:
    {{- include "mariadb-cluster.labels" . | nindent 4 }}
spec:
  {{- with .Values.mariadb.affinity }}
  affinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.args }}
  args:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.bootstrapFrom }}
  bootstrapFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.command }}
  command:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.connection }}
  connection:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.database }}
  database: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.env }}
  env:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.envFrom }}
  envFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.galera }}
  galera:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.image }}
  image: {{ .Values.mariadb.image }}
  {{- end }}
  {{- with .Values.mariadb.imagePullPolicy }}
  imagePullPolicy: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.inheritMetadata }}
  inheritMetadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.initContainers }}
  initContainers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.livenessProbe }}
  livenessProbe:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.maxScale }}
  maxScale:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.maxScaleRef }}
  maxScaleRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.metrics }}
  metrics:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.myCnf }}
  myCnf: |
    {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.myCnfConfigMapKeyRef }}
  myCnfConfigMapKeyRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.passwordPlugin }}
  passwordPlugin:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.passwordSecretKeyRef }}
  passwordSecretKeyRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.podDisruptionBudget }}
  podDisruptionBudget:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.podMetadata }}
  podMetadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.podSecurityContext }}
  podSecurityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.port }}
  port: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.primaryConnection }}
  primaryConnection:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.primaryService }}
  primaryService:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.priorityClassName }}
  priorityClassName: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.readinessProbe }}
  readinessProbe:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.replicas }}
  replicas: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.replicasAllowEvenNumber }}
  replicasAllowEvenNumber: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.replication }}
  replication:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rootPasswordSecretKeyRef:
    {{- toYaml .Values.rootPasswordSecretKeyRef | nindent 4 }}
  {{- with .Values.mariadb.secondaryConnection }}
  secondaryConnection:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.secondaryService }}
  secondaryService:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.securityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.serviceAccountName }}
  serviceAccountName: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.servicePorts }}
  servicePorts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.sidecarContainers }}
  sidecarContainers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.startupProbe }}
  startupProbe:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.storage }}
  storage:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.suspend }}
  suspend: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.timeZone }}
  timeZone: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.topologySpreadConstraints }}
  topologySpreadConstraints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.username }}
  username: {{ . }}
  {{- end }}
  {{- with .Values.mariadb.volumeMounts }}
  volumeMounts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mariadb.volumes }}
  volumes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
