apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: azurite-key
stringData:
  # Ref: https://github.com/Azure/Azurite?tab=readme-ov-file#default-storage-account
  storageAccountKey: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
